### ISSUE TITLE
Wrong Typescript Definition

### ISSUE THREAD

**Issue by josephsls510** [nuxt/lmify#70] opened 2022-12-22 02:48 UTC
The typescript definition does not match the actual JS implementation.

Expect: 
```ts
let dir = ''
// expect no type error
setRootDir(dir)
```

Result:
```bash
file.ts:97:16 - error TS2554: Expected 0 arguments, but got 1.

97     setRootDir(dir);
                  ~~~
```

**Comment by nozomuikuta** [comment] 2023-02-22 16:53
Duplicate of #47, whose PR (#46) is in review.

**Closed as completed by nozomuikuta** 2023-02-22 16:53 UTC
